baseURL: http://localhost:1313/
title: NYC Redistricting Project
enableRobotsTXT: yes
enableEmoji: yes
theme: hugo-theme-jane
hasCJKLanguage: yes
paginate: 3
rssLimit: 20
disqusShortname: ''
googleAnalytics: ''
copyright: ''
defaultContentLanguage: en
languages:
  en:
    languageCode: en
author:
  name: Sam
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
menu:
  main:
    - identifier: home
      name: Home
      pageref: /
      weight: 10
    - identifier: archives
      name: Archives
      pageref: /post/
      weight: 20
    - identifier: tags
      name: Tags
      pageref: /tags/
      weight: 30
    - identifier: categories
      name: Categories
      pageref: /categories/
      weight: 40
    - name: external-link
      pageref: https://gohugo.io
      weight: 50
params:
  contentCopyright: <a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/"
    target="_blank">CC BY-NC-ND 4.0</a>
  customCSS: []
  customJS: []
  dateFormatToUse: '2006-01-02'
  description: Hugo theme jane example site.
  homeFullContent: no
  keywords:
    - Hugo
    - theme
    - jane
  logoTitle: Transit
  photoswipe: yes
  rssFullContent: yes
  since: '2017'
  social:
    a-email: 'samtgoodson@gmail.com'
  toc: yes
